-- Autonomous Agents
-- Migration: 003_autonomous_agents.sql

-- AUTONOMOUS TASKS
-- Stores tasks for background agents to process.
create table if not exists autonomous_tasks (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  task_type text not null check (task_type in ('goal_analysis', 'memory_consolidation', 'knowledge_graph_update', 'project_monitor', 'content_advisor')),
  task_payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'processing', 'completed', 'failed')),
  result jsonb,
  created_at timestamp with time zone default now(),
  completed_at timestamp with time zone
);

-- AUTONOMOUS INSIGHTS
-- Stores insights generated by background agents.
create table if not exists autonomous_insights (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  agent_type text not null,
  insight text not null,
  confidence float default 0.5,
  metadata jsonb default '{}'::jsonb,
  acknowledged boolean default false,
  created_at timestamp with time zone default now()
);

-- INDEXES
create index if not exists autonomous_tasks_user_id_idx
  on autonomous_tasks (user_id);

create index if not exists autonomous_tasks_status_idx
  on autonomous_tasks (status);

create index if not exists autonomous_tasks_type_idx
  on autonomous_tasks (task_type);

create index if not exists autonomous_insights_user_id_idx
  on autonomous_insights (user_id);

create index if not exists autonomous_insights_agent_type_idx
  on autonomous_insights (agent_type);
